baseURL = "https://fal-works.github.io/make-games-with-p5js/"
author = "FAL"
languageCode = "ja-jp"
hasCJKLanguage = true
title = "p5.js でゲーム制作"
theme = "book"
publishDir = "docs"
[params]
  BookRepo = 'https://github.com/fal-works/make-games-with-p5js'
  BookSearch = false
  title = "p5.js でゲーム制作"
  description = "JavaScript と p5.js を使って、一からゲームを作り上げるまでの過程をレクチャーします。Flappy Bird を題材にしていますが、他のゲームにも応用可能です。"
  # images = ["site-feature-image.jpg"]
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 2
