baseURL = "https://fal-works.github.io/make-games-with-p5js/"
author = "FAL"
languageCode = "ja-jp"
hasCJKLanguage = true
title = "p5.js でゲーム制作"
theme = "book"
pygmentsCodeFences = true
publishDir = "docs"
[params]
  BookRepo = 'https://github.com/fal-works/make-games-with-p5js'
  BookSearch = false