baseURL = "https://fal-works.github.io/make-games-with-p5js/"
author = "FAL"
languageCode = "ja-jp"
hasCJKLanguage = true
title = "p5.js でゲーム制作"
theme = "book"
publishDir = "docs"
[params]
  BookRepo = 'https://github.com/fal-works/make-games-with-p5js'
  BookSearch = false
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 2